# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(5,2)
arr3 = np.array([11,12,13,14,15,16,17,18,19,20]).reshape(5,2)
np.vstack((arr2,arr3))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(5,2)
arr5 = np.array([11,12,13,14,15,16,17,18,19,20]).reshape(5,2)
np.hstack((arr4,arr5))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [20]:
arr6 = np.arange(30).reshape(3,5,2)
print(arr6)
np.reshape(arr6,(30))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [16]:
arr6 = np.arange(30).reshape(3,2,5)
print(arr6.ndim)
np.reshape(arr6,(30)).ndim

3


1

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [25]:
arr7 = np.arange(30)
print(arr7.ndim)
np.reshape(arr7,(5,2,3)).ndim

1


3

## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
arr8 = np.arange(25).reshape(5,5)
print(arr8)
np.square(arr8)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [34]:
arr9 = np.arange(30).reshape(5,6)
f"The mean of he array {arr9.std()}"

'The mean of he array 8.65544144839919'

## Question:9

### Find the standard deviation of the previous array in Q8?

In [37]:
f"The standard daviation of the above array {arr9.std()}"

'The standard daviation of the above array 8.65544144839919'

## Question:10

### Find the median of the previous array in Q8?

In [48]:
np.median(arr9)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [51]:
arr9.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [66]:
arr10 = np.arange(5,21).reshape(4,4)
print(arr10)
np.trace(arr10)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


50

## Question:13

### Find the determinant of the previous array in Q12?

In [67]:
np.linalg.det(arr10)

1.3755762034791435e-29

## Question:14

### Find the 5th and 95th percentile of an array?

In [69]:
arr11 = np.arange(50)
print("5th percentile of arr : ", 
       np.percentile(arr11, 5))
print("95th percentile of arr : ", 
       np.percentile(arr11, 95))

5th percentile of arr :  2.45
95th percentile of arr :  46.55


## Question:15

### How to find if a given array has any null values?

In [4]:
arr12 = np.arange(25).reshape(5, 5)             
print("\nIs NaN: \n", np.isnan(arr12)) 
arr13 = [[1,2,3,4],  
     [np.nan,2,2,2]] 
print("\nIs NaN: \n", np.isnan(arr13)) 


Is NaN: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]

Is NaN: 
 [[False False False False]
 [ True False False False]]
